on:
    pull_request: 
        branches:
            - "main"
            - "develop"

name: Tests

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install asdf & tools
              uses: asdf-vm/actions/install@v4
              with:
                skip_install: true
            - run: |
                asdf plugin add nodejs
                asdf plugin add bun
                asdf install nodejs 20.16.0
                asdf install bun 1.1.42