on:
    pull_request: 
        branches:
            - "main"
            - "develop"

name: Tests

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - run: |
                echo "nodejs 20.16.0" > .tool-versions
                echo "bun 1.1.42" > .tool-versions
            - name: Install asdf & tools
              uses: asdf-vm/actions/install@v4
